# Generated by Django 4.2.3 on 2023-07-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_alter_taskaccess_reciever'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='anyone_can_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tasks',
            name='anyone_can_update',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='TaskAccess',
        ),
    ]
