# Generated by Django 4.2.3 on 2023-07-24 20:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0008_remove_taskupdateapplications_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskupdatelog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
